# with the help of https://jlelse.blog/dev/drone-dind
kind: pipeline
name: default
type: docker

steps:
  - name: build
    image: plugins/docker
    settings:
      username: snaprojectuser
      password:
        from_secret: docker_password
      repo: snaprojectuser/front
      tags: latest
      cache_from:
        - snaprojectuser/front:latest
      dry_run: true

  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host:
        # - 45.137.190.96  # machine is down
        - 45.137.190.92
      username: root
      port: 22
      key:
          from_secret: ssh_key
      script:
        - docker pull snaprojectuser/front:latest
        - docker stop front
        - docker rm front
        - docker run -d --name front -p 80:3070 snaprojectuser/front:latest
        - docker ps

trigger:
  branch:
    - master
  event:
    - push