# with the help of https://jlelse.blog/dev/drone-dind
kind: pipeline
name: default
type: docker

steps:
  - name: build
    image: plugins/docker
    environment:
      - DOCKER_BUILDKIT: 1
    settings:
      username: snaprojectuser
      password:
        from_secret: docker_password
      repo: snaprojectuser/front
      tags:
        - "${DRONE_BRANCH}"
        - "${DRONE_BRANCH}-${DRONE_COMMIT}"
      cache_from:
        - "snaprojectuser/front:master"
        - "snaprojectuser/front:${DRONE_BRANCH}"
      dry_run: false

  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host:
        # - 45.137.190.96  # machine is down
        - 45.137.190.92
      username: root
      port: 22
      key:
          from_secret: ssh_key
      script:
        - docker pull snaprojectuser/front:master
        - docker stop front
        - docker rm front
        - docker run -d --name front -p 80:3070 snaprojectuser/front:master
        - docker ps

trigger:
  branch:
    - master
  event:
    - push